# Javascript - Node.js - CD


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  workingDirectory: 'functions'
  displayName: 'npm install'

- script: npm install -g firebase-tools
  workingDirectory: 'functions'
  displayName: 'npm install firebase-tools'

- script: firebase deploy --project joachimveulemans-kmphby
  workingDirectory: 'functions'
  displayName: 'firebase deploy'
